// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

package frc.robot;

import frc.robot.commands.*;
import frc.robot.subsystems.*;
import main.java.frc.robot.subsystems.SwerveSubsystem;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command.InterruptionBehavior;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.InstantCommand;

 
public class RobotContainer {
  //subsystems
  private static RobotContainer m_robotContainer = new RobotContainer();
  private final SwerveSubsystem swerveSubsystem = new SwerveSubsystem();

  //controller
  private final XboxController m_driveController = new XboxController(1);


  public RobotContainer() {
    swerveSubsystem.setDefaultCommand(new SwerveJoystickCmd(
      swerveSubsystem,
      () -> -m_driveController.getRawAxis(DriveConstants.kDriverYAxis),
      () -> m_driveController.getRawAxis(DriveConstants.kDriverXAxis),
      () -> m_driveController.getRawAxis(DriveConstants.kDriverRotAxis),
      () -> !m_driveController.getRawButton(DriveConstants.kDriverFieldOrientedButtonIdx)));

    configureButtonBindings();
  }

  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  private void configureButtonBindings() {
    new JoystickButton(m_driveController, 2).whenPressed(() -> swerveSubsystem.zeroHeading());
  }

  public Command getAutonomousCommand() {
    return null;
  }
  

}

